var express = require('express')
var bodyParser = require('body-parser')
var port = process.env.PORT || 8000
var xmlparser = require('express-xml-bodyparser')
var session = require('express-session')
var path = require('path')

var app = require('express.io')()
app.http().io()

app.set('views', __dirname + '/../views')
app.engine('jade', require('jade').__express)
app.set('view engine', 'jade')

app.use(express.static(__dirname + '/../public'))
app.use(bodyParser.json())
app.use(bodyParser.urlencoded({extended: true}))

app.get('/:id', function(req, res) {
    //res.render(req.params.id)
    console.log(req.params.id)
    res.render('users/welcome')
})

var success = 'Testing'
var images = { user: 'naultran',
  project: 'RNTest',
  images:
   [ { imgName: '22_Default_001_087_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_087_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{ 'metrics': 'rance2', 'name': 'name'}],
       qcOutput: 'GOOD',
       userInput: null },
     { imgName: '22_Default_001_098_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_098_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_089_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_089_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_090_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_090_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_091_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_091_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_092_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_092_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_093_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_093_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_094_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_094_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_095_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_095_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_096_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_096_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_097_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_097_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null },
     { imgName: '22_Default_001_088_Image',
       image: '/cors_demo/naultran/RNTest/22_Default_001_088_Image.jpeg',
       QC: [{ 'metrics': 'rance', 'name': 'name'},{'metrics': 'rance2','name':'name'}],
       qcOutput: 'BAD',
       userInput: null } ] }
var set_name = 'Testing'
var modules = ['Oil Red O']
var projArray = [ { project: 'RNTest', sets: [ 'RNTest_verified' ] } ]
var ProjList = [ 'RNTest' ]

images = JSON.stringify(images)
app.get('/:dir/:view', function(req,res) {
    console.log(req.params.dir)
    console.log(req.params.view)
    res.render(req.params.dir + '/' + req.params.view, { success: success, img: images, set: set_name, projects: projArray, modules: modules, sets: ProjList } )
})

app.listen(port, function() {
  console.log('Listening on port ' + port)
})

